export type OrderStatus = 'DRAFT' | 'PENDING' | 'ACCEPTED' | 'FILLED' | 'PARTIALLY_FILLED' | 'CANCELLED' | 'TIMEOUT' | 'RECONCILED' | 'REJECTED'

export interface Order {
  cid: string               // client order id (idempotent key, generated by us)
  exchangeOrderId?: string  // exchange-side order id (returned by Bitfinex)
  status: OrderStatus
  instrument: string
  direction: 'long' | 'short'
  size: number
  price: number
  orderType: 'limit' | 'market'
  fillPrice?: number
  fillSize?: number
  fee?: number
  createdAt: number
  updatedAt: number
  retryCount: number
  strategyId: string
}
